README.adoc

Edit Intro for README

---

platform/client/src/AppContainer.tsx
platform/client/src/components/Map.tsx
platform/client/src/components/Router.tsx
platform/client/src/context/AuthContext.tsx
platform/client/src/pages/ActionPage.tsx
platform/client/src/pages/ProfilePage.tsx

- fix volunteer state in ProfilePage when a new volunteer is created
- remove some unused imports from Actions and Map components

Fix volunteer profile state

---

platform/client-admin/package.json
platform/client-admin/src/components/Map.tsx
platform/client/src/components/Map.tsx

@wtrocki type definition file was there for the `client` app but not the `client-admin`
Can you try this PR and see how it goes?

fix: re-enable map and add missing GM types mappings in the client-admin app

---

platform/client-admin/src/pages/ViewActionPage.tsx

fix: find action by id

---

platform/client-admin/src/components/Router.tsx
platform/client-admin/src/forms/recipient.ts
platform/client-admin/src/forms/volunteer.ts
platform/client-admin/src/pages/ViewVolunteerPage.tsx
platform/client-admin/src/transformer/volunteerTransformer.ts

feat: edit volunteer

---

platform/client-admin/src/components/Router.tsx
platform/client-admin/src/forms/recipient.ts
platform/client-admin/src/pages/RecipientsPage.tsx
platform/client-admin/src/pages/ViewRecipientPage.tsx

feat: edit recipient

---

platform/README.adoc
platform/client-admin/README.adoc
platform/client/README.adoc
platform/package.json
platform/server/README.md

chore: add generate all commands to do a one shot queries and resolvers generation

---

platform/README.adoc

docs: fix openshift deployment artefacts location

---

platform/client-admin/src/components/Menu.tsx
platform/client-admin/src/components/Router.tsx
platform/client-admin/src/components/model/Product.tsx
platform/client-admin/src/components/model/ProductList.tsx
platform/client-admin/src/dataFacade.tsx
platform/client-admin/src/forms/product.ts
platform/client-admin/src/graphql/fragments/DistributionCentreExpanded.graphql
platform/client-admin/src/graphql/fragments/ProductExpanded.graphql
platform/client-admin/src/graphql/fragments/VolunteerActionProductExpanded.graphql
platform/client-admin/src/graphql/queries/findIdAndNamesOfAllDistributionCentres.graphql
platform/client-admin/src/pages/CreateProductPage.tsx
platform/client-admin/src/pages/ProductsPage.tsx
platform/client-admin/src/pages/RecipientsPage.tsx
platform/client-admin/src/pages/ViewProductPage.tsx
platform/client-admin/src/pages/ViewRecipientPage.tsx
platform/client-admin/src/pages/ViewVolunteerPage.tsx
platform/client/src/dataFacade.tsx
platform/client/src/graphql/fragments/DistributionCentreExpanded.graphql
platform/client/src/graphql/fragments/ProductExpanded.graphql
platform/client/src/graphql/fragments/VolunteerActionProductExpanded.graphql
platform/model/main.graphql
platform/server/src/resolvers/models.ts
platform/server/src/resolvers/resolvers.ts
platform/server/src/schema/schema.graphql

feat: add product crud operations

---

platform/client-admin/samples.graphql
platform/client-admin/src/components/Router.tsx
platform/client-admin/src/components/model/Volunteer.tsx
platform/client-admin/src/dataFacade.tsx
platform/client-admin/src/forms/create-volunteer.ts
platform/client-admin/src/forms/recipient.ts
platform/client-admin/src/forms/volunteer.ts
platform/client-admin/src/graphql/fragments/Volunteer.graphql
platform/client-admin/src/graphql/fragments/VolunteerActionExpanded.graphql
platform/client-admin/src/graphql/fragments/VolunteerExpanded.graphql
platform/client-admin/src/pages/CreateRecipientPage.tsx
platform/client-admin/src/pages/CreateVolunteerPage.tsx
platform/client-admin/src/pages/RecipientsPage.tsx
platform/client-admin/src/pages/ViewVolunteerPage.tsx
platform/client-admin/src/pages/VolunteersPage.tsx
platform/client/samples.graphql
platform/client/src/dataFacade.tsx
platform/client/src/forms/volunteer.ts
platform/client/src/graphql/fragments/Volunteer.graphql
platform/client/src/graphql/fragments/VolunteerActionExpanded.graphql
platform/client/src/graphql/fragments/VolunteerExpanded.graphql
platform/client/src/pages/ProfilePage.tsx
platform/model/main.graphql
platform/server/src/schema/schema.graphql

create recipient and volunteer

---

platform/server/src/mongo/createMongoServices.ts

fix: set version field when creating model

---

platform/.openshift/amq.yml
platform/.openshift/ovp-app-template.yml

fix: renames datasync to ovp in openshift templates

---

platform/client-admin/samples.graphql
platform/client-admin/src/dataFacade.tsx
platform/client-admin/src/forms/volunteer-action-recipient.ts
platform/client-admin/src/forms/volunteerAction.ts
platform/client-admin/src/graphql/queries/findVolunteerActionDetails.graphql
platform/client-admin/src/pages/ViewActionPage.tsx

feat: display volunteer action products

---

platform/client-admin/package.json
platform/client-admin/src/components/Router.tsx
platform/client-admin/src/components/model/Product.tsx
platform/client-admin/src/forms/createVolunteerAction.ts
platform/client-admin/src/forms/volunteerAction.ts
platform/client-admin/src/pages/ActionPage.tsx
platform/client-admin/src/pages/CreateProductPage.tsx
platform/client-admin/src/pages/CreateVolunteerAction.tsx
platform/client/package.json

feat: create volunteer action

---

platform/server/src/mongo/createMongoServices.ts

Reverts aerogear/OpenVolunteerPlatform#64

Revert "fix: set version field when creating model"

---

platform/client-admin/package.json
platform/client/package.json

fix: uniforms dependency issue

---

platform/client-admin/src/pages/ActionPage.tsx
platform/client-admin/src/pages/DistributionCentrePage.tsx
platform/client-admin/src/pages/ProductsPage.tsx
platform/client-admin/src/pages/RecipientsPage.tsx
platform/client-admin/src/pages/VolunteersPage.tsx

fix: use ion-fab button

---

platform/client-admin/src/dataFacade.tsx
platform/client-admin/src/graphql/fragments/DistributionCentreExpanded.graphql
platform/client-admin/src/graphql/fragments/RecipientExpanded.graphql
platform/client-admin/src/graphql/fragments/VolunteerAction.graphql
platform/client-admin/src/graphql/fragments/VolunteerActionExpanded.graphql
platform/client-admin/src/graphql/fragments/VolunteerActionProductExpanded.graphql
platform/client-admin/src/graphql/fragments/VolunteerExpanded.graphql
platform/client-admin/src/pages/ViewActionPage.tsx
platform/client/src/dataFacade.tsx
platform/client/src/graphql/fragments/DistributionCentreExpanded.graphql
platform/client/src/graphql/fragments/RecipientExpanded.graphql
platform/client/src/graphql/fragments/VolunteerAction.graphql
platform/client/src/graphql/fragments/VolunteerActionExpanded.graphql
platform/client/src/graphql/fragments/VolunteerActionProductExpanded.graphql
platform/client/src/graphql/fragments/VolunteerExpanded.graphql
platform/client/src/pages/ViewActionPage.tsx
platform/model/main.graphql

Lay the ground work for https://github.com/aerogear/OpenVolunteerPlatform/issues/79 while waiting for https://github.com/aerogear/graphback/issues/1314

chore: add assignedAt and completedAt timestamps in VolunteerAction model

---

platform/client-admin/samples.graphql

chore: add action reports queries

---

README.adoc
docs/gettingstarted.md
platform/README.adoc

Platfom docs

---

docs/integrations_graphback_keycloak.md

There are roles created actually - we using adming for this, but working on fixing some issue to really enable it. Next alpha will have it :D

docs: add how to customize keycloak rules

---

docs/coding.md
platform/README.md
platform/server/README.md
platform/server/docker-compose.yml
platform/server/integrations/keycloak/initKeycloak.js

feat: import sample volunteers into Keycloak

---

platform/server/src/AMQCrudService.ts
platform/server/src/config/auth.ts

Minor fix to use rules we have build

fix: Enforce authz rules for keycloak

---

platform/server/src/config/keycloak.json
platform/server/src/resolvers/custom-resolvers.ts

also activate authz for assigning volunteers mutation

fix: use correct clientId in server for authz

---

platform/client-admin/src/config/MarkerIcons.ts
platform/client-admin/src/pages/ActionsMapPage.tsx
platform/client-admin/src/pages/ViewActionPage.tsx
platform/client/src/components/Map.tsx
platform/client/src/pages/ViewActionPage.tsx

feat: display directions on volunteer app

---

docs/coding.md
docs/platform_starter.md
platform/README.md
platform/client-admin/src/AppContainer.tsx

1) fixing typings that broke master - disabled auto updates for that as well. 
2) Removing invalid information from documentation - adding proper user names.

Fix typings

---

platform/datasync-server/configs/auth.json
platform/datasync-server/configs/keycloak.json
platform/datasync-server/functions/typescript/generated/customContext.ts
platform/datasync-server/functions/typescript/generated/generated-types.ts
platform/datasync-server/functions/typescript/generated/index.ts
platform/datasync-server/functions/typescript/taskResolvers.ts
platform/datasync-server/model/model.graphql

Add datasync example

---

platform/datasync-server/model/model.graphql

fix: Add streamable

---

platform/client/package.json
platform/client/src/context/AuthContext.tsx
platform/client/src/datastore/generated/schema.json
platform/package.json

This PR adds the ability to filter models at network level. See related PR for Offix:
https://github.com/aerogear/offix/pull/982

feat: add late initialization for model filtering
